# Week2授業前課題3 行列積のスクラッチ

## 【問題1】行列積を手計算する

In [322]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

$$
\boldsymbol{A*B} =
\left[\begin{array}{c}
-1 \times 0 + 2 \times 0 + 3 \times 2\quad &
-1 \times 2 + 2 \times 2 + 3 \times 9\quad &
-1 \times 1 + 2 \times -8 + 3 \times -1 \\ 
4 \times 0 + -5 \times 0 + 6 \times 2\quad &
4 \times 2 + -5 \times 2 + 8 \times 9\quad &
4 \times 1 + -5 \times -8 + 6 \times -1  \\
7 \times 0 + 8 \times 0 + -9 \times 2\quad &
7 \times 2 + 8 \times 2 + -9 \times 9\quad &
7 \times 1 + 8 \times -8 + -9 \times -1 
\end{array}\right]
\boldsymbol{} =
\left[\begin{array}{c}
6 & 29 & -20 \\
12 & 70 & 38 \\
-18 & -51 & -48
\end{array}\right] \quad
$$




## 【問題2】NumPyの関数による計算

In [323]:
np.dot(a_ndarray,b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [324]:
np.matmul(a_ndarray,b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [325]:
a_ndarray@b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 【問題3】ある要素の計算を実装

In [326]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

sum00 = sum(a_ndarray[0,:]*b_ndarray[:,0])
print("Aの0行目とBの0列目の合計は {}です。".format(sum00))

Aの0行目とBの0列目の合計は 6です。


## 【問題4】行列積を行う関数の作成

In [327]:
def calc_sum(a_ndarray, b_ndarray):
    
    sum_array = np.empty((a_ndarray.shape[0],a_ndarray.shape[0]))
    
    for i in range(a_ndarray.shape[0]):
        for j in range(b_ndarray.shape[1]):
            sum_array[i,j] = sum(a_ndarray[i,:]*b_ndarray[:,j])

    return sum_array

In [328]:
calc_sum(a_ndarray, b_ndarray)

array([[  6.,  29., -20.],
       [ 12.,  52.,  38.],
       [-18., -51., -48.]])

## 【問題5】計算が定義されない入力を判定する

In [329]:
# 問題4の関数を修正

def calc_sum2(a_ndarray, b_ndarray):
    
    if a_ndarray.shape[0] == b_ndarray.shape[1]:
        sum_array = np.empty((a_ndarray.shape[0],a_ndarray.shape[0]))

        for i in range(a_ndarray.shape[0]):
            for j in range(b_ndarray.shape[1]):
                sum_array[i,j] = sum(a_ndarray[i,:]*b_ndarray[:,j])

        return sum_array
    else:
        print("形に問題があるため、計算ができません。")

In [330]:
d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
calc_sum2(d_ndarray_, e_ndarray)

形に問題があるため、計算ができません。


## 【問題6】転置

In [331]:
calc_sum2(d_ndarray_.T, e_ndarray)

array([[ 33., -28.,   9.],
       [-48.,  41.,  -6.],
       [  9.,  -6.,  45.]])